name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: Platane/snk@v3.5.0
        with:
          github_user_name: Sbasnayaka
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the generated files to the 'output' branch
      - name: Push snake to output branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: output
          force: true
          directory: ./output
          github_token: ${{ secrets.GITHUB_TOKEN }}